export const SET_AUTH_TOKEN_START = 'SET_AUTH_TOKEN_START';
export const SET_AUTH_TOKEN_SAGA = 'SET_AUTH_TOKEN_SAGA';
export const SET_AUTH_TOKEN_SUCCESS = 'SET_AUTH_TOKEN_SUCCESS';
export const SET_AUTH_TOKEN_FAIL = 'SET_AUTH_TOKEN_FAIL';
